### ISSUE TITLE
After issuing VC via CHAPI, LCW shows error

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/learner-credential-wallet#547]
Steps to reproduce:

1. Go through wallet setup again. (Uninstall / reinstall app, or go to Settings > Reset Wallet, and relaunch the app).
2. This time, don't skip the Register step. Click on Register Wallet. You'll be taken to the register web page. click Register there. Then switch back to the wallet
3. Now lets get a VC into the wallet (from flow 1).
4. Go to https://vcplayground.org/issuer (in your mobile browser)
5. In the upper right of the playground issuer webpage, click the Settings gear, select VC-API to any Wallet
6. Click Issue Verifiable Credential blue button.
7. Click Skip DID Authentication

This should open LCW and present you with the VC, and an Accept/Decline screen. Error is seen here.

> Seeing this in iOS:
> 
> ![screenshot_2024-01-23_at_1 47 07___pm](https://github.com/digitalcredentials/learner-credential-wallet/assets/3487193/fce9b548-770c-4414-8a00-3579e5f00162)
> 
>  

 _Originally posted by @alexfigtree in [#263](https://github.com/digitalcredentials/learner-credential-wallet/issues/263#issuecomment-1906727748)_

**Comment by dmitrizagidulin** [comment]
This has been fixed in the RN branch, PR #550

**Comment by alexfigtree** [comment]
@dmitrizagidulin Just tested this. Error is still happening, showing the same screenshot as above. Tested on iOS. Moving back to ToDo.

**Comment by alexfigtree** [comment]
Re-testing needed on build 81

**Comment by alexfigtree** [comment]
Not showing error, but also not reflecting in the app. Currently see the option of choosing between many wallets (Veres demo) before getting to LCW. Could also be blocked by #638 .

**Comment by alexfigtree** [comment]
Build 82: Works in iOS, although the cred being imported is missing info:

![Image](https://github.com/user-attachments/assets/6ae7a5ea-5485-42c2-abb3-86bb561f6c69)
![Image](https://github.com/user-attachments/assets/42f0ad1c-573d-4954-934a-b4869de707a6)

**Comment by alexfigtree** [comment]
Issue complete, moving to Done
